name: Notify PR Opened When Weekdays
on:
  pull_request:
    types: [opened]

jobs:
  notify-pr-opened-when-weekdays:
    name: Notify PR Opened When Weekdays
    runs-on: ubuntu-latest
    steps:
      - name: Set current day of the week
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DAY_OF_WEEK=$(date +'%u')" >> $GITHUB_ENV

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if : ${{ env.CURRENT_DAY_OF_WEEK < 6 }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GitHub Actions
          SLACK_COLOR: success
          SLACK_MESSAGE: |
            *${{ github.event.issue.title}}*
            ${{ github.event.issue.html_url }}
          SLACK_TITLE: Issue Created